load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_test(
    name = "binary_search_test",
    srcs = ["binary_search_test.cc"],
    deps = [
        "//lib:binary_search",
	"@googletest//:gtest_main"
    ],
)
