load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
    name = "binary_search",
    srcs = ["binary_search.cc"],
    hdrs = ["binary_search.h"],
    visibility = ["//test:__pkg__"],
)
